

services:
  postgres:
    image: postgres:15-alpine
    container_name: quizbee-db
    environment:
      POSTGRES_DB: quizbee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quizbee-network

  backend:
    build: .
    container_name: quizbee-backend
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Usa 'dev' para desarrollo local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quizbee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - quizbee-network

volumes:
  postgres_data:

networks:
  quizbee-network:
    driver: bridge